# Generated by Django 3.1.7 on 2022-03-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc_fid', models.IntegerField()),
                ('featurecla', models.TextField()),
                ('name', models.TextField()),
                ('elevation', models.FloatField()),
                ('comment', models.TextField()),
                ('name_alt', models.TextField()),
                ('lat_y', models.FloatField()),
                ('long_x', models.FloatField()),
                ('nation1', models.TextField()),
                ('nation2', models.TextField()),
                ('note', models.TextField()),
                ('region', models.TextField()),
                ('subregion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
