# Generated by Django 3.0.1 on 2022-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20220319_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('wkb_geometry', models.TextField()),
                ('featurecla', models.TextField()),
                ('name', models.TextField()),
                ('elevation', models.FloatField()),
                ('comment', models.TextField()),
                ('name_alt', models.TextField()),
                ('lat_y', models.FloatField()),
                ('long_x', models.FloatField()),
                ('nation1', models.TextField()),
                ('nation2', models.TextField()),
                ('note', models.TextField()),
                ('region', models.TextField()),
                ('subregion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Geodata',
        ),
    ]
