# Generated by Django 3.0.1 on 2022-03-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20220321_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
